### ISSUE TITLE
Agregar el nombre del driver

### ISSUE THREAD

**Issue by orenteriab** [orenteriab/kinnil#1]
Agregar el nombre del driver cuando se asigne un driver (eventos.evento  de "TMS ACCEPTED" a "Assigned to <Driver Name>")

**Comment by orenteriab** [comment]
@dotmaik1 ¿del socket viene el driver id? ¿O de dónde va a venir el nombre del driver?

**Comment by orenteriab** [comment]
@dotmaik1 estoy viendo que, los eventos están actualizando tickets, no eventos.evento. ¿Me puedes clarificar en dónde vamos a poner esto?

**Comment by dotmaik1** [comment]
![image](https://user-images.githubusercontent.com/21315569/46899547-f30a2000-ce51-11e8-815c-b2d6b53722a3.png)

Aqui tiene que decir Acepter y nombre del vato

**Comment by dotmaik1** [comment]
el nombre puede ser sacado cuando nos mandan el primer evento "TMS ACCEPTED" ahi nos proporcionan el id del ticket con eso podemos sacar el id del hr en la columna hr_id y de ahi el nombre

o podemos agregar un evento con el nombre en cuanto asignemos el ticket al driver ahi si tenemos hr_id devolada   

exports.assignTicket = (hrId, ticketId) => {

**Comment by orenteriab** [comment]
Done

**Comment by dotmaik1** [comment]
Thnks
