### ISSUE TITLE
Nuevo cliente - dispatcher

### ISSUE THREAD

**Issue by dotmaik1** [orenteriab/kinnil#10]
Al momento de trabajar los tickets (tobe assigned, work in progress y completed) es necesario que el Dispatcher pueda distinguir sobre que cliente esta trabajando (halliburton, diamonback, etc)

Veo 2 posibles soluciones, ayúdame a revisarlas o si tu tienes mas ideas de como podemos hacer esto te escucho @orenteriab  

1era propuesta:

Agregar una columna nueva a los grids que sea "Client" y que aparezcan todos los tickets en una misma pagina y ellos puedan  utilizar el search de bootgrid para filtrar y decidir cuales quieren ver.

![image](https://user-images.githubusercontent.com/21315569/47971124-81398680-e04b-11e8-8805-b6f0d1edd3e2.png)

2da propuesta agregar un combobox a la pagina donde puedan seleccionar el cliente y solo les aparezcan los tickets de ese cliente en particular, (En esta opción abría que tener cuidado de dejar seleccionado al cliente No. 1 por default [halliburton] para que no se vea el grid vacio hasta que seleccionen un cliente

**Comment by dotmaik1** [comment]
Que propones @orenteriab ?

**Comment by orenteriab** [comment]
@dotmaik1 la primera me parece que funciona mejor.

**Comment by dotmaik1** [comment]
Excelente, entonces nos vamos con esa

**Comment by orenteriab** [comment]
Este ya quedó en assigned, work in progress y completed.

Pásame el script de la tabla de divert para ponerlo ahí también.

**Comment by dotmaik1** [comment]
Ya mande la tabla en un dump en whatsapp

**Comment by dotmaik1** [comment]
Gracias
