### ISSUE TITLE
Periodo en el PDF

### ISSUE THREAD

**Issue by orenteriab** [orenteriab/kinnil#2]
En el PDF, se debe de incluir el periodo de la semana pasada próxima de Domingo 00:00 h y acaba el sábado 23:59:59 (pdf de payroll)

	-Esto en base a la fecha de compleated (VALIDACIÓN POR PARTE DE DISPATCH) (tickets.completed_date)

**Comment by orenteriab** [comment]
@dotmaik1: ¿Esto se va a mostrar tipo: "Period: Sep 30 - Oct 06"?

**Comment by dotmaik1** [comment]
exactamente, para la semana del 7 al 13 Oct

**Comment by orenteriab** [comment]
Done

**Comment by dotmaik1** [comment]
thnks
