### ISSUE TITLE
Quitar el rate y el % del pdf (Payroll)

### ISSUE THREAD

**Issue by orenteriab** [orenteriab/kinnil#3]

**Comment by orenteriab** [comment]
@dotmaik1 ¿Recuerdas en dónde está el %?

**Comment by dotmaik1** [comment]
![image](https://user-images.githubusercontent.com/21315569/46899501-6e1f0680-ce51-11e8-8260-55ccab43488e.png)

**Comment by orenteriab** [comment]
Done

**Comment by dotmaik1** [comment]
thnks
