### ISSUE TITLE
Incluir la columna de "demerge amount"

### ISSUE THREAD

**Issue by orenteriab** [orenteriab/kinnil#4]
(vacío y para que escriban) $ 0.0 (solo acepta numeros con 2 decimales) (esto es en payroll)

	-Esta columna es el monto que se va a pagar por las horas de "stand by time"
	-Se tiene que agregar este monto a la suma del total para el PDF de payroll
	-No se va amostrar en el pdf (horas demerge) sólo el $$$
	-Este monto va arriba del total en el PDF
	-En el cálculo solo deben de mostrarse 2 decimales

**Comment by orenteriab** [comment]
@dotmaik1 el demerge es por ticket?

**Comment by dotmaik1** [comment]
te averiguo lo mas seguro es que si

**Comment by orenteriab** [comment]
¡Listo!

Hay que agregar la columna 

`alter table sandras.payroll_hr add column(demerge double);`

**Comment by dotmaik1** [comment]
Thanks
