### ISSUE TITLE
Incluir la columna de "stand by time" 

### ISSUE THREAD

**Issue by orenteriab** [orenteriab/kinnil#5]
a la izquiera de load rate (payroll) y debe de mostrar un valor numérico (4.8 hrs, .75 hrs, etc)

	-El standby time es la diferencia de horas entre arrived to location y unloading
	-Agregar la columna tickets.standby_time y llenar esta informacion cuando lleguen los eventos

**Comment by orenteriab** [comment]
Done

**Comment by dotmaik1** [comment]
Thanks
