### ISSUE TITLE
Agregar columna Loading Date 

### ISSUE THREAD

**Issue by orenteriab** [orenteriab/kinnil#6]
(tickets.loading_date) enseguda de la columna "Load" a todos las tablas exceptuando To Be Assigned

	-Hay que serciorarse que la columna ya esta en la DB si no solamente agregarla con un alter table
	-La fecha de esta columna se va a alimentar cuando ocurra el evento de loading (substatus =  3.- LOADING) en los sockets

**Comment by orenteriab** [comment]
Done

**Comment by dotmaik1** [comment]
Thanks
