### ISSUE TITLE
Nuevo cliente - Carga de CSV

### ISSUE THREAD

**Issue by dotmaik1** [orenteriab/kinnil#7]
Al subir un csv con cargas para el nuevo cliente hay que tener las siguientes consideraciones:

1. Se agregara una nueva columna al los csv "Shipper" que contendrá el nombre del cliente ( de momento solo seran 2 "HALLIBURTON" y "DIAMONBACK") hay que guardar en sandras.tickets.clients_id el ID correspondiente a ese cliente.

2. Para el cliente DIAMONBACK no van a incluir la columna de Rate Invoice, hay que ver que no truene el código si no la incluyen.

3. Hay que crear un acolumna para almacenar el numero de millas que vienen en el csv (ticket["Miles"])

**Comment by orenteriab** [comment]
Trabajando en este.

**Comment by dotmaik1** [comment]
Thnks
