### ISSUE TITLE
Nuevo cliente - Administrative

### ISSUE THREAD

**Issue by dotmaik1** [orenteriab/kinnil#9]
Necesitamos que en el área de administrativa se puedan agregar, editar y eliminar Crews, Locations, Facilities, Products y Sands para los nuevos clientes, esto no es tan difícil, ya esta casi todo el codigo preparado para en administrative_controller.js 

![image](https://user-images.githubusercontent.com/21315569/47971061-7500f980-e04a-11e8-9cd0-1235e0cc6948.png)

solo hay que obtener el ID del cliente de la ULR (http://cedar.sandrevolution.com:3000/web/administrative/clients/[ID del cliente]) y hacer los post de ajax incluyendo ese ID 

hay algunos que no reciben el ID del cliente, hay que verificar si necesitan ese Id, o ya son eliminados y editados correctamente con su mismo Id

![image](https://user-images.githubusercontent.com/21315569/47971069-b0032d00-e04a-11e8-8b2c-3831f01177ed.png)

**Comment by dotmaik1** [comment]
Pls agrega el nuevo cliente directamente en tu DB para que puedas entrar directamete en http://cedar.sandrevolution.com:3000/web/administrative/clients

insert into clients (name, active) values ('DIAMONBACK', 1);

**Comment by dotmaik1** [comment]
insert into clients (name, active) values ('DIAMONBACK', 1);

**Comment by orenteriab** [comment]
f1fdd057294f2cad48cdcd2e45cf7f0fa9120030

**Comment by orenteriab** [comment]
Quedó
f1fdd057294f2cad48cdcd2e45cf7f0fa9120030
15e4abc4ec7baafcde19669d06c5708fa56e3a58
9a3d136302336421dc9a160ea2d576b1b663bf1c

**Comment by dotmaik1** [comment]
Gracias
